apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyGateway
gateway:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
logging:
  level:
    default: info
provider:
  type: Kubernetes
extensionApis:
  enableBackend: true
  enableEnvoyPatchPolicy: true
extensionManagers:
  - name: ai-gateway
    failOpen: false
    hooks:
      xdsTranslator:
        translation:
          listener:
            includeAll: true
          route:
            includeAll: true
          cluster:
            includeAll: true
          secret:
            includeAll: true
        post:
          - Translation
          - Cluster
          - Route
    service:
      fqdn:
        hostname: ai-gateway-controller.envoy-ai-gateway-system.svc.cluster.local
        port: 1063
  - name: custom-extproc
    failOpen: false
    hooks:
      xdsTranslator:
        translation:
          listener:
            includeAll: true
          route:
            includeAll: true
          cluster:
            includeAll: true
        post:
          - Translation
    service:
      fqdn:
        hostname: custom-ext-server.envoy-ai-gateway-system.svc.cluster.local
        port: 1063
